# Generated by Django 2.2 on 2022-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectApp', '0004_auto_20220410_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
